### ISSUE TITLE
Consider using gogo/protobuf as protobuf library

### ISSUE THREAD

**Issue by beorn7** [prometheus/client_model#15]
https://github.com/gogo/protobuf creates faster and less allocation-heavy protobuf code, and arguably more idiomatic code.

Perhaps this is something that can be done while moving over to proto3, as we have to change the code using the protobuf API anyway at that time.

@juliusv

**Comment by kyessenov** [comment]
Is this still active? I'd like to import `metrics.proto` in gogo-compiled code, and would like to see it hosted here. There're minor differences between go/gogo (extra methods). Would you be OK to publish it here under `gogo` directory? Can you point me to the toolchain that generated the hosted code?

**Comment by beorn7** [comment]
This is certainly something being considered. Since the current state of the library exposes some protobuf details, it would probably be a breaking change. Since other protobuf related parts are in flux right now (move to proto3, future of protobuf usage in the Prometheus ecosystem in general), I don't want to make hasty changes in master right now. (I'm currently working on the upcoming non- or only moderately-breaking changes for v0.9. After that, we'll tackle more heavily breaking changes for v0.10, which is ideally the version that gets us on track to a v1.0 release.)
Prior to v0.10, it would definitely be very helpful to gain experience with gogo/protobuf usage. To avoid confusion until then, it would, however, be better to do that in a branch or in a fork of this repo.

**Comment by beorn7** [comment]
As it stands now, future work on protobuf for Prometheus exposition will be based on OpenMetrics, if it happens at all. Once we are there, we should certainly consider alternative protobuf implementations like gogo/protobuf, but it's not even clear if that will happen in this repo. More likely is that this repo will disappear. In any case, pointing to gogo/protobuf from here right now is a red herring. (Cf. https://github.com/prometheus/client_golang/issues/303 as the tracking issue in client_golang.)

Thus, closing this here.
