### ISSUE TITLE
improve commentary on Histogram and Bucket

### ISSUE THREAD

**Issue by tschottdorf** [prometheus/client_model#16]
``` proto
message Bucket {
  optional uint64 cumulative_count = 1; // Cumulative in increasing order.
  optional double upper_bound = 2;      // Inclusive.
}

message Histogram {
  optional uint64 sample_count = 1;
  optional double sample_sum   = 2;
  repeated Bucket bucket       = 3; // Ordered in increasing order of upper_bound, +Inf bucket is optional.
}
```

There are unclear points to me. Perhaps this is documented somewhere; certainly not in this repo (the README.md could link if there are resources elsewhere I should have looked at).
- isn't `sample_count` just the last bucket's `cumulative_count`?
- isn't `sample_sum` derivable by iterating through the buckets? If that is true, is it optional to specify it? Also, upon second thought, what am I summing up `count*upper_bound`?

An example in the comment would be illuminating.

**Comment by beorn7** [comment]
> isn't sample_count just the last bucket's cumulative_count?

Yes. That's why `+Inf bucket is optional.`

> isn't sample_sum derivable by iterating through the buckets?

No. `sample_sum` is the sum of observations, same as in a Summary. Summing up the buckets would only give an approximation of that.
https://prometheus.io/docs/concepts/metric_types/#histogram

**Comment by tschottdorf** [comment]
Thanks Björn. The Histogram I was scraping didn't collect the sum, so it didn't even occur to me that there was a loss of fidelity there.
