### ISSUE TITLE
Please release current version to pip

### ISSUE THREAD

**Issue by deathowl** [prometheus/client_model#17]
The version available on pip: https://pypi.python.org/pypi/prometheus_client_model/0.0.1 does not support histograms. Please release the current version as a pip package.
Thanks.

**Comment by brian-brazil** [comment]
That package is not in use. I suggest using the official Python Client: https://github.com/prometheus/client_python/

**Comment by deathowl** [comment]
Dear @brian-brazil . I would need the new version of the package to make protobuf available in client_python.

**Comment by brian-brazil** [comment]
We don't control that package. You're also likely to run into requirements for the Python client (such as no deps in core) that'll make it impractical to implement there.

**Comment by deathowl** [comment]
So if no deps in core is so important( i can totally understand that) there are two options for me:
- Disable protobuf serialization support if no protobuf package is installed.
- Separate protobuf serialization into a separate package, this would result in some duplicated code tho.

**Comment by grobie** [comment]
@matttproud would need to either upload a new package version or give someone else access to that package.

**Comment by deathowl** [comment]
once the new package is released i'll send the PR regarding these changes: **https://github.com/deathowl/client_python/commits/protobuf**

**Comment by beorn7** [comment]
@deathowl This appears stale. Are there any updates?

**Comment by beorn7** [comment]
Closing due to staleness. Please follow up if needed.
