### ISSUE TITLE
No such gem prometheus-client-model

### ISSUE THREAD

**Issue by mmikulicic** [prometheus/client_model#21]
```
gem install prometheus-client-model
```

```
ERROR:  Could not find a valid gem 'prometheus-client-model' (>= 0) in any repository
```

(there is no https://rubygems.org/gems/prometheus-client-model)

Would it be possible to publish this gem?

**Comment by brian-brazil** [comment]
This repository isn't used much these days. You probably want to use https://github.com/prometheus/client_ruby

**Comment by beorn7** [comment]
Closing due to staleness.
