### ISSUE TITLE
rubygems.org contains bad version of prometheus client model.

### ISSUE THREAD

**Issue by xtreme-andrew-su** [prometheus/client_model#29]
The version published to rubygems.org is not the actual prometheus client model gem. It contains code for "hello world".

I propose two options:
- Publish the actual gem even if it is not maintained anymore
- Remove the current gem from rubygems.org and update the documentation to mention deprecation and suggest alternatives.

https://rubygems.org/gems/prometheus-client-model/versions/1.0.0

**Comment by beorn7** [comment]
@grobie do you have context on this issue?

**Comment by grobie** [comment]
I don't know who has uploaded that Gem, that's not me and I have never heard of that handle. I don't think we can do much here, besides asking that person to take down that gem.

**Comment by beorn7** [comment]
@grobie In the [README.md](https://github.com/prometheus/client_model/blob/f287a105a20ec685d797f65cd0ce8fbeaef42da1/ruby/README.md) for Ruby, thele is a line `gem install prometheus-client-model`. Doesn't that install the Gem mentioned by @xtreme-andrew-su ? You added the README.md in https://github.com/prometheus/client_model/commit/775af9440e07a658e13f699448c745367bc12115 .

**Comment by grobie** [comment]
Yes it does. IIRC correctly this was in preparation for adding protobuf support to client ruby. We can remove the readme or reach out that user asking them to delete that stub gem so that we can publish the actual gem.

**Comment by beorn7** [comment]
Hmm, how to contact the owner of a gem on rubygems.org? For now, I'll remove the misleading line.

**Comment by beorn7** [comment]
@xtreme-andrew-su I'm closing this now as the misleading install instructions have been removed. If you know a way to contact the owner of the gem, feel free to encourage them to update (or remove) it.

**Comment by xtreme-andrew-su** [comment]
@beorn7 I took a look at the other gems that person has uploaded. It looks like they're just name squatting .. most if not all are "hello world". May need to contact the maintainers of rubygems.org or file an abuse claim.

**Comment by xtreme-andrew-su** [comment]
I've opened an abuse claim: http://help.rubygems.org/discussions/problems/34812-reporting-abuse-on-prometheus-client-model?unresolve=true feel free to chime in

**Comment by beorn7** [comment]
Many thanks @xtreme-andrew-su . Since you linked this issue there, I guess we won't need to chime in. But if rubygems.org requires my direct intervention, I'll happily do so.

**Comment by xtreme-andrew-su** [comment]
@beorn7 The current owner of the gem has responded to the ticket. I've posted an update requesting to transfer ownership to you at the email specified in your github profile. Please reply to the ticket on rubygems.org or reach out to the owner if that info is incorrect.

**Comment by beorn7** [comment]
I would actually prefer to remove the gem altogether. The Ruby client of Prometheus doesn't support protobuf, and since even the Prometheus server dropped protobuf support (much to my dismay), there are no plans to add it ever. Use cases for this gem would be quite niche at best, and I don't think we should encourage its usage at the moment by providing a gem. (Nor do I want to invest efforts in maintaining it.) For power users that need it for some reason, there is still the code in this repo.
