### ISSUE TITLE
../vendor/github.com/prometheus/client_golang/prometheus/summary.go:330:31: cannot use s.objectives (type map[float64]float64) as type float64 in argument to quantile.NewTargeted

### ISSUE THREAD

**Issue by shaojintian** [prometheus/client_model#34]
`../vendor/github.com/prometheus/client_golang/prometheus/summary.go:330:31: cannot use s.objectives (type map[float64]float64) as type float64 in argument to quantile.NewTargeted
`

**Comment by beorn7** [comment]
This problem seems to be related to prometheus/client_golang, not prometheus/client_model. Could you open an issue there? When doing so, please include more context when and where this is happening. Thanks!
