### ISSUE TITLE
Add a suitable deprecation notice

### ISSUE THREAD

**Issue by beorn7** [prometheus/client_model#37]
This repo is essentially only used (within the Prometheus project) by prometheus/client_golang. There might be external users, of course, but prometheus/prometheus doesn't consume protobufs anymore since v2.0.0. This should be noted prominently in the README.md.

**Comment by brian-brazil** [comment]
Maybe we could remove all bar the Go uses? We can always add things back in as needed if that ends up making sense OM wise.

**Comment by beorn7** [comment]
I'll give it a spin.

**Comment by brian-brazil** [comment]
Though thinking on it for OM we'd probably end up with the protos over in the OpenObservability org for all the languages, but that's not something that we've talked about.

**Comment by beorn7** [comment]
I would also expect the OM proto definitions to live somewhere else. This repo will most likely get graveyarded eventually.
