### ISSUE TITLE
How to add exemplars to pure Native Histograms

### ISSUE THREAD

**Issue by beorn7** [prometheus/client_model#61]
How to deal with exemplars if there are only sparse buckets but no conventional buckets?

We probably need a separate section in the protobuf spec. (There will also be the interesting question how to pick exemplars, but that's not the concern of the exposition format.)

**Comment by beorn7** [comment]
Note that this issue doesn't block merging the sparsehistogram branch of this repo into the master branch. This feature can be added later without a breaking change.

**Comment by fstab** [comment]
OpenTelemetry solved this by just adding a list of Exemplars. Sounds like this would work for Prometheus as well? https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/metrics/v1/metrics.proto#L557

**Comment by beorn7** [comment]
Yes, so we will simply have a repeated exemplar message as an additional field in native histograms. Note, though, that we have to require timestamps for those exemplars (which also happens to be in line with OTel). See https://github.com/prometheus/prometheus/pull/13021 for context.

**Comment by fatsheep9146** [comment]
@beorn7 can I pick up this issue?

**Comment by beorn7** [comment]
Yes, sure. Thank you.
