### ISSUE TITLE
MetricFamily is missing UNIT

### ISSUE THREAD

**Issue by cmordue** [prometheus/client_model#68]
The OpenMetrics specification says that [UNIT metadata is required for metric families](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#metricfamily) but it is not present in the [MetricFamily proto](https://github.com/prometheus/client_model/blob/master/io/prometheus/client/metrics.proto#L148).

**Comment by beorn7** [comment]
That's because it is not the OpenMetrics protobuf spec, but the spec for the classic Prometheus protobuf format.

The OpenMetrics protobuf spec is here: https://github.com/OpenObservability/OpenMetrics/blob/main/proto/openmetrics_data_model.proto
